name: build-nix-iso
on:
  workflow_dispatch:
    inputs:
      target:
        description: Target builder folder containing a default.nix file to build an ISO
        required: true
        default: laptop
      
jobs: 
  build-target-image:
    name: Build target image
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: cachix/install-nix-action@7ac1ec25491415c381d9b62f0657c7a028df52a7 # v24
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Install Homemanager
      run: nix-channel --add https://github.com/rycee/home-manager/archive/master.tar.gz home-manager
    - name: Check nix.conf
      run: cat /etc/nix/nix.conf
    - name: Build NixOS Image
      run: |
        nix-build '<nixpkgs/nixos>'  \
          -A config.system.build.isoImage \
          -I nixos-config=./configuration.nix \
          --option sandbox false
    - uses: actions/upload-artifact@v3
      with:
        name: nixos.iso
        path: ./result/iso/*.iso*
