name: build-nix-iso
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      target:
        description: Target builder folder containing a default.nix file to build an ISO
        required: true
        default: laptop
      
jobs: 
  build-target-image:
    name: Build target image
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: cachix/install-nix-action@7ac1ec25491415c381d9b62f0657c7a028df52a7 # v24
    - name: Add Home Manager channel
      run: nix-channel --add https://github.com/rycee/home-manager/archive/master.tar.gz home-manager
    - name: Add NixOS Unstable
      run: nix-channel --add https://nixos.org/channels/nixos-unstable nixos
    - name: Update Channels
      run: nix-channel --update
    - name: Check nix.conf
      run: cat /etc/nix/nix.conf
    - name: Build NixOS Image
      run: nix build .#nixosConfigurations.iso.config.system.build.isoImage
    - uses: actions/upload-artifact@v3
      with:
        name: nixos.iso
        path: ./result/iso/*.iso*
